- NKL/KLR.lean
This is the portable format, and the target of tracing.
> feat: define KLR representation

- NKL/Encode.lean
The KLR language is the official intermediate format. This patch ports the serialization and deserialization code to this new data type.
> chore: port encoder to KLR

- Main.lean
- bin/klr
- lake-manifest.json
- lakefile.lean
This allows us to add more subcommands for things like linting and lsp serving. No new commands added yet.
> Add CLI library

- .gitignore
- bin/make-wheel
- interop/MANIFEST.in
- interop/README.md
- interop/klr/parser.py
- interop/pyproject.toml
This creates a wheel in the pypi test repository.
It is OSX only (or whatever architecture you run it on) so it is not ready for prime time, but can be used for demos and gives the guts of what a real solution will look like.
> POC: Create a Python wheel

- .github/workflows/ci.yml
> Run CI on OSX and Linux

- .github/workflows/ci.yml
> fix: tweak pypi publishing config

- .github/workflows/ci.yml
- bin/check-libs
- lakefile.lean
Our binary is not running on Linux. This is exploratory.
> List dynamic libraries

- interop/pyproject.toml
Want new wheels to try arm linux
> chore: Bump version to 0.0.7

- .github/workflows/ci.yml
https://github.com/leanprover/lean-action/issues/116#issuecomment-2663316227
> ci: Workaround for github action crashes

- .github/workflows/ci.yml
- interop/pyproject.toml
- lake-manifest.json
- lakefile.lean
- lean-toolchain
> chore: Update to Lean 4.16.0

- KLR/Trace/NKI.lean
- KLR/Trace/Tensor.lean
- interop/nki/isa/__init__.py
- interop/nki/language/__init__.py
- interop/pyproject.toml
- interop/test/apis.py
- interop/test/test_nki_allocation.py
This change builds on the proir additions of pointers and memory views to implement the NKI allocation API.
> feat: implement NKI allocation API

- KLR/Trace.lean
- KLR/Trace/Basic.lean
- KLR/Trace/Builtin.lean
- KLR/Trace/NKI.lean
- KLR/Trace/Numpy.lean
- KLR/Trace/Tensor.lean
Adds a new command for defining built-in functions. The nki command is similar to def, but handles translation of the Python arguments to Lean using the FromNKI type class.
> feat: add nki command for defining builtin functions

- Main.lean
When plugging tools together, it's nice if the default is to use stdout.
There is probably a better way to do this.
> chore: print to stdout by default

- KLR.lean
- KLR/Util.lean
- KLR/Util/SHA256.lean
Will use this for NEFF packaging
> feat: Add SHA256

- KLR/NRT/leannrt.c
This was a source of undefined behavior/segfault in an error condition.
> fix: Declare all variables before gotos in NRT ffi

- KLR/Util.lean
- KLR/Util/Json.lean
- HashMap instances for BEq, FromJson, ToJson
- Drop null values from objects for equality
- Check round tripping a data structure is the identity (mod null values)
- Encoding Nats as Json Strings
> feat: Add json utilities

- KLR/Serde/Basic.lean
- KLR/Serde/Elab.lean
This change adds instances for ToCBOR for basic types.
> feat: ToCBOR instances for basic types

- KLR/Util.lean
- KLR/Util/Hex.lean
Slightly more user friendly than base64
> feat: Add hex encoding to Util

- KLR/Util.lean
- KLR/Util/Json.lean
- KLR/Util/ListJson.lean
Required when the Json consumer has bugs.
> feat: ListJson - control the order of json object keys

- KLR/Serde/Basic.lean
- KLR/Serde/Elab.lean
- KLR/Serde/Test.lean
Similar to ToCBOR---handles mutual inductives.
> feat: add FromCBOR deriving

- KLR/Trace/Python.lean
This patch adds an assignment to subscript `x[s] = e`.
This is an important case because, when x is a location to the memory and e is `nki.language.load`, it must immediately store to the location (e.g., when s is ellipse, `t[...] = nl.load` must achieve a full simple copy).
Previously, when the RValue function is traversing e, it could have created a temporary access (Tensor.load), so this could not be achieved. This problem is addressed in this patch by making the `assign` function not call `RValue` and making `assignTerm` function probe whether the RHS was `.store`.
After this patch, the only remaining unsupported case in `nki_matmul_tiled_` is `res_psum += nl.matmul`.
> Add support for assignment to subscript (x[s] = e)

- KLR/Trace/Python.lean
This patch supports an alternative form of tracing `x = f()` and `x binop= f()` when this is necessary.
Specifically, this is for supporting lowering of `res_psum += nl.matmul(...)` NKI to KLR.
The Python tracer was first unfolding this to `res_psum = res_psum + nl.matmul(...)`, but this has two issues:
1. It has to expand `exprOp : BinOp -> Expr -> Expr -> Trace Term` when the second argument of exprOp is Core.Expr.call. However, in this case, it is not clear how the output of `exprOp` can be represented in Term. One possible solution is to temporarily store the output of `nl.matmul` into a temporary buffer (in SBUF or PSUM or anywhere) and use the access as the second argument of `exprOp`, but then the following issue appears.
2. I understood that `res_psum += nl.matmul(...)` is …
> feat: trace `x = f()` and `x binop= f()` with fn keyword args

- KLR/Serde/File.lean
- Main.lean
- interop/klr/serde.c
- interop/pyproject.toml
Doing a release to get the new source distribution uploaded to PyPi.
> chore: update version for release

- KLR/Util/SexpParser.lean
We are trying to move parsers from home-grown stuff to a standard set of combinators. This is an experiment with Lean builtins like Parsec, Position, FileMap etc. Seems better to me.
> chore: Use Lean's Parsec/FileMap/etc for parsing

- KLR/Core/Tensor.lean
- KLR/Trace/Basic.lean
Not sure why it's needed by got a second hand request that it will be good to have
> chore add flattenedFreeElements to TensorSram

- KLR/Serde/Basic.lean
> fix: number decoding

- KLR/Core/Basic.lean
- KLR/Core/Operators.lean
- KLR/Core/Tensor.lean
- KLR/File.lean
- KLR/Python.lean
- KLR/Serde/Basic.lean
- KLR/Trace.lean
- KLR/Trace/Basic.lean
- KLR/Trace/FromNKI.lean
- KLR/Trace/ISA.lean
- KLR/Trace/NKI.lean
- KLR/Trace/Python.lean
- Main.lean
Mostly changes to naming needed for easy C++ code generation, but also some minor fixes to the new ISA instructions.
> fix: minor fixes to partial evaluator

- KLR/Util/Enum.lean
This makes it easy to tell what the order will be, useful for set-like operations.
> chore: Sort Enum.values by numeric value

- KLR/Extract/Extract/C.lean
- KLR/Extract/Extract/Serde.lean
- interop/klr/ast_file.h
- interop/klr/ast_klir.h
- interop/klr/ast_nki.h
- interop/klr/ast_python_core.h
- interop/klr/frontend.c
- interop/klr/gather.c
- interop/klr/serde_file.c
- interop/klr/serde_klir.c
- interop/klr/serde_klir.h
- interop/setup.py
*Note:* Only the Lean code is important, the changes to the C code are from re-running the generator.
> chore: update C codegen to produce C++ compatible code

- KLR/NKI.lean
- KLR/NKI/Patterns.lean
- Main.lean
Adding some simple transformations to make the partial evaluator less complex.
> feat: add pass to simplify complex patterns

- interop/klr/frontend.c
- interop/klr/frontend.h
- interop/klr/gather.c
- Adds support for Pytorch tensors
- Adds debatable handling of grid parameter. For now, we only need a minimalist simple integer to represent the number of cores to run the function on.
> Support Pytorch Tensors & Grid Parameter

- KLR/Util/Enum.lean
Macros are lighter weight, and I was able to debug this faster. If an inductive is private, You need private on any method you want to use postfix.
> fix: Switch Enum from Elab to Macro, fix private toUInt8

- KLR/Util/Sexp.lean
- KLR/Util/ToBytes.lean
These are the easy cases. FromBytes is coming.
> chore: Add Vector to NumBytes, ToSexp, FromSexp

- KLR/Trace/NKI.lean
- interop/klr/gather.c
Github is messed up, it thinks this was merged.
> fix: allow pre-production kernel namespace

- KLR/Trace/NKI.lean
- KLR/Trace/Term.lean
Github is messed up, it thinks this was merged.
> feat: add some missing operators

- KLR/Trace/Term.lean
Github is messed up, it thinks this was merged.
> feat: add nl.ds function

- interop/klr/gather.c
- Support Jax tensors which have the same structure as numpy tensors.
> Handle Jax Tensors

- KLR/Trace/NKI.lean
Allow returns from kernels like:
```
def foo(a, b):
a_out, b_out = f(a, b)
return (a_out, b_out)
####
def bar(a,b):
a_out, b_out = f(a, b)
return [a_out,b_out]
#####
def f1():
l = [1, 2]
return l
def foo1(a,b,c):
l = f1()
l[0] = 0
return l
####
def f(a,b,c):
l = [a, b, c]
return l
def foo(a,b,c):
return f(a,b,c)
```
> Fix: references and complicated types should show up in outputs

- KLR.lean
- KLR/Compile.lean
- Main.lean
- interop/klr/Makefile
- interop/klr/frontend.c
- interop/klr/frontend.h
- interop/klr/serde.c
Also fixed the imports in Compile.lean
> chore: cleanup some unused code

- KLR/Py/Basic.lean
- KLR/Trace/FromNKI.lean
- KLR/Trace/NKI.lean
- KLR/Trace/Tensor.lean
- KLR/Trace/Term.lean
- KLR/Trace/Types.lean
When we encounter unexpected expression we should let user know which expression was not supported.
> Feat: better error messaging during tracing

- KLR/NKI/SimplifyOperators.lean
The problem here is that we can't just match on `\`builtin.lang.ndarray` as it comes through as `nl.ndarray` in this section.
Do a hacky solution for now to unblock people writing kernels and come back to it with a better solution
> fix: naming of view and ndarray

- KLR/Util/Padding.lean
This allows you to treat Padding like a Vector
> feat: Add GetElem instance to Padding

- KLR/Compile/Pass.lean
- KLR/NKI/Simplify.lean
- KLR/Trace.lean
- KLR/Trace/ISA.lean
- KLR/Trace/NKI.lean
- KLR/Trace/Types.lean
Converted Trace to Pass transformer
> Feat: convert Trace monad to Pass transformer
