Export.lean
NKL/Encode.lean
NKL/NKI.lean
NKL/PrettyPrint.lean
interop/nkl/loader.py
interop/test/test_json.py

This change brings the NKI AST closer to the original Python AST, at the expense of losing some syntactic constraints. This will make it easier to do more of the processing on the Lean side.

refactor: remove Index type from AST

---

Main.lean
NKL.lean
NKL/FFI.lean
NKL/Python.lean
interop/nkl/parser.py

Introduces a direct representation of the python abstract syntax, and a simple parser for python functions. This is necessary to support the formalization of the tracing process.

feat: support for python syntax

---

NKL/FFI.lean
NKL/Python.lean
interop/nkl/parser.py

Add ability to capture global references, including function arguments when parsing kernels. Globals and arguments are directly encoded as KLR terms.

feat: add global references and arguments

---

NKL/Trace.lean
NKL/Trace/Basic.lean
NKL/Trace/Tensor.lean

Basic tracing of Terms in the inner TraceM monad.

feat: basic tracing for Terms

---

NKL/FFI.lean
NKL/Python.lean
NKL/Trace.lean
NKL/Trace/Basic.lean
NKL/Trace/NKI.lean
NKL/Trace/Python.lean
interop/test/test_basic.py

This patch adds basic tracing for user python functions. The main code
is in Python.lean, and depends on definitions in Basic.lean and
NKI.lean, which are incomplete. As more primitives are implemented,
more user kernels will be supported.
Note to reviewers: it may be helpful to check the tests in `interop/tests/test_basic.py`.

Tracing for python source functions

---

NKL/FFI.lean
NKL/KLR/Basic.lean
NKL/KLR/Encode.lean
NKL/KLR/Pretty.lean
NKL/Trace/Python.lean
NKL/Trace/Tensor.lean

This change adds two related things: a pretty-printer for KLR terms, and tensor names. Tensor names make the pretty printing nicer, but have a second purpose. By naming all of the tensors, we can scan a KLR kernel to collect up all of the input, output, and intermediate tensors that will be needed to run the kernel. For argument tensors, the generated tensor names are changed to the argument variable names; this is just for readability.

A simple pretty-printer for KLR

---

NKL/Trace/Python.lean
interop/test/test_basic.py

This change adds support for assignment like: `x, y = z`. Python calls this "unpacking", and you can convert between lists and tuples as long as they are the right length.

feat: add assignments to tuples and lists

---

NKL/FFI.lean
NKL/KLR/Basic.lean
NKL/KLR/Encode.lean
NKL/Python.lean
NKL/Trace.lean
NKL/Trace/Basic.lean
NKL/Trace/Builtin.lean
NKL/Trace/Python.lean
NKL/Trace/Types.lean
NKL/Util.lean

This patch cleans up a few cases of partial definitions, making them total. There is also a small amount of refactoring and renaming to be consistent with TensorLib.

refactor: make some partial functions total

---

NKL/Python.lean
NKL/Trace/Basic.lean
NKL/Trace/Builtin.lean
NKL/Trace/NKI.lean
NKL/Trace/Python.lean
NKL/Trace/Tensor.lean
NKL/Trace/Types.lean

The main change in this patch is to extend the Object structure with new functions for indexing and binary operators. In addition, the operator names have been converted from strings to enumerations, and the translation of index expressions has been reworked to allow more flexibility. For instance, the new implementation can now support `t[f()]` where f is an arbitrary user function or builtin.

feat: extend builtin object capabilities

---

.github/workflows/ci.yml
.gitignore
bin/make-wheel
interop/MANIFEST.in
interop/README.md
interop/klr/parser.py
interop/noop.c
interop/pyproject.toml

This took a lot of time to figure out, but we can generate linux and osx wheels now on GitHub Actions that seem functional on both systems. Will probably hit problems, e.g. with different Mac OSs, but I suspect that the right tweaks cibuildwheel arguments will be able to fix those.
[Example run](https://github.com/leanprover/KLR/actions/runs/13218433309) (among a graveyard of failed attempts).

CI: Make a wheel

---

.github/workflows/ci.yml
README.md
bin/rename-wheels
interop/pyproject.toml

Publishes to both test.pypi.org and pypi.org on tag pushes.
Example artifacts: https://test.pypi.org/project/klr/0.0.3/#files

ci: Publish to pypi.org

---

.github/workflows/ci.yml

This went missing when I tried to do the pypi upload on tag pushes.

fix: re-add dropped section of build file

---

.github/workflows/ci.yml

We currently aren't building ARM wheels. I'm not sure this will work, but let's try it. We only push the wheels on the main branch, so we need to merge this to try it.
Build works:
https://github.com/leanprover/KLR/actions/runs/13293628967/job/37120447588

ci: Add arm build host

---

KLR.lean
KLR/Core.lean
KLR/Core/Basic.lean
KLR/Core/FromToJson.lean
KLR/Core/Pretty.lean
KLR/Python.lean
KLR/Trace.lean
KLR/Trace/Basic.lean
KLR/Trace/Builtin.lean
KLR/Trace/NKI.lean
KLR/Trace/Numpy.lean
KLR/Trace/Python.lean
KLR/Trace/Tensor.lean
KLR/Trace/Types.lean
Main.lean

This patch adds the ability to track needed tensor allocations during the tracing process. To do this, a new `store` statement and term expression are added.  A more complete implementation of the tensor_scalar operator is included as a test case for the new mechanism.

feat: track tensor allocations during tracing

---

KLR/Python.lean
bin/gather
interop/klr/parser.py
interop/test/test_basic.py

Our current Python parser does not notice undefined symbols. While we don't do anything with them now, we want to pass that info back to the caller in the forthcoming linter. In addition, we intended parsing to fail when there are undefined symbols, as indicated in test_basic.py, but it was failing for an unrelated reason before, and broke a few commits ago.
This change just makes a best effort attempt to notice undefined symbols, and crashes accordingly in the klr binary. In the future we will do more with this.
This change fixes the broken CI build.

feat: Detect undefined symbols

---

.github/CODEOWNERS
CODEOWNERS

The previous CODEOWNER file was in the wrong place, at the root. It is only picked up by github in .github/CODEOWNERS or docs/CODEOWNERS. I didn't realize we had a file bc the repo wasn't showing us as having one.

Add CODEOWNERS

---

KLR/Util.lean
Main.lean
bin/make-wheel
bin/run-bir
interop/MANIFEST.in

Adds some scripts and cli improvement to run gather and nki-to-bir without requiring explicit PYTHONPATH munging.
The run-bir script has some hard-coded paths at the moment, but
we should be able to get more general, or at least give a
list of instructions for getting the right setup as a followup.
This adds `gather` to the wheel, so we can run from the wheel.
For example
$ lake build
$ bin/make-wheel
$ cd /tmp
$ virtualenv env
$ source env/bin/activate
$ pip install ~/workplace/sherloc/KLR/.wheel/dist/klr_lang-0.0.7-cp313-cp313-macosx_14_0_arm64.whl
$ env/lib/python3.13/site-packages/bin/klr nki-to-bir ~/workplace/sherloc/KLR/interop/test/test_nki_isa_tensor_scalar.py kernel1
{"version": 2,
"functions":
[{"name": "sg0000",
...

feat: Scripts to generate and run BIR

---

KLR/BIR/Compile/Memory.lean
KLR/BIR/Function.lean
KLR/Core/Basic.lean
KLR/Core/FromToJson.lean
KLR/Core/Operators.lean
KLR/Core/Pretty.lean
KLR/Python.lean
KLR/Trace/Basic.lean
KLR/Trace/FromNKI.lean
KLR/Trace/Numpy.lean
KLR/Trace/Python.lean
KLR/Trace/Tensor.lean
KLR/Trace/Types.lean
interop/test/test_basic.py

This patch fills in the implementation of tensor_scalar, and also refactors some code to make this easier. The main change is the introduction of specific element types (`Dtype`) as specified in the NKI docs.

feat: implement all tensor_scalar ALU ops and types

---

KLR/Python.lean
KLR/Trace.lean
KLR/Trace/Basic.lean
KLR/Trace/Builtin.lean
KLR/Trace/FromNKI.lean
KLR/Trace/NKI.lean
KLR/Trace/Numpy.lean
KLR/Trace/Python.lean
KLR/Trace/Tensor.lean
KLR/Trace/Types.lean
KLR/Util.lean
Main.lean

This change removes the ability to place lean functions inside the trace environment, and simplifies the trace monad types. Builtin functions are now represented in the environment by their unique names. When a builtin is encountered, we use the name to dispatch to the correct lean function. This dispatching is fixed and cannot be changed at runtime.

refactor: remove Object type and Tracer monad

---

KLR/BIR/Compile/Kernel.lean
KLR/BIR/Compile/Memory.lean
KLR/BIR/Instruction.lean
KLR/Core/Basic.lean
KLR/Core/FromToJson.lean
KLR/Core/Operators.lean
KLR/Core/Pretty.lean
KLR/Trace/Basic.lean
KLR/Trace/Builtin.lean
KLR/Trace/FromNKI.lean
KLR/Trace/Python.lean
KLR/Trace/Tensor.lean
KLR/Trace/Types.lean
interop/test/test_basic.py

This change removes IndexExpr and adds a hardware-based access method (Access.pattern). This change is motivated by the new loop semantics which does not include an explicit affine loop. A future change will add a fully dynamic loop and related access forms.

refactor: simplify KLR based on new loop design

---

KLR/BIR/Compile/Kernel.lean
KLR/Core/Basic.lean
KLR/Core/Pretty.lean
KLR/Trace/FromNKI.lean
KLR/Trace/Python.lean
KLR/Trace/Tensor.lean
KLR/Trace/Types.lean

This change makes a small change to KLR so that it can support unknown function calls. The store statement is changed so that it can only be used with an operator, and the call expression is used for unknown functions.

feat: allow unknown functions in KLR

---

Main.lean
interop/pyproject.toml

It seems like good practice to bump the version right after a release.

chore: bump version number to v0.0.9

---

KLR/BIR/Compile/Memory.lean
KLR/Core/Basic.lean
KLR/Core/FromToJson.lean
KLR/Core/Pretty.lean
KLR/Trace/Basic.lean
KLR/Trace/Python.lean
KLR/Trace/Tensor.lean
KLR/Trace/Types.lean

This changes adds invariants, in the form of proof terms, to several of the Core types. Once the types are constructed, the invariants can be relied upon. As a general rule, we do not use the invariants directly in code that we want to prove things about, to avoid dependent pattern matching.  Rather, we use an error monad and then prove a theorem that guarantees the computation will not fail by using the invariants.

feat: add invariants to Core types

---

KLR/BIR/Compile/Kernel.lean
KLR/Trace/FromNKI.lean
KLR/Trace/Python.lean
KLR/Util.lean

The triangle notation was introduced to get around a limitation in Lean that couldn't prove termination when mapM was used, even if it was structurally
obvious. I didn't like the notation solution because it seemed brittle; I tried replacing the notation with a def and an abbrev, but neither worked. I still don't understand why it works, but I also don't understand why
| .tuple es .store => return .tuple (<- es.attach.mapM fun ⟨ e, _ ⟩ => LValue e)
works but
| .tuple es .store => return .tuple (<- es.attach.mapM fun e => LValue e.val)
does not. Since this is now required in only 2 spots (thanks likely to improvements in Lean itself) I propose we just remove the notation and do the trick until it's no longer needed.

chore: remove the triangle notation

---

KLR/Python.lean
KLR/Trace/Basic.lean
KLR/Trace/Python.lean
Main.lean

Small modifications to Python AST to make it easier to automatically generate equivalent C and Python versions. Changes include: replacing single constructor inductive types with structures, replacing Prod types with structures, renaming some constructors to avoid conflicts, replacing HashSet with List.

refactor: make Python AST more amenable to extraction to C

---

KLR.lean
KLR/NKI.lean
KLR/NKI/Basic.lean
KLR/Python.lean

This change introduces the abstract syntax of NKI.  This change is part of a larger effort to break KLR up into smaller passes that can be more easily compared with the upcoming C++ implementation. The first of these passes will be a simplification pass that consumes the Python Core AST and produces the NKI AST (contained in this patch).

feat: introduce NKI abstract syntax

---

KLR.lean
KLR/NEFF.lean
KLR/NEFF/Basic.lean
Main.lean

Example:
$ bin/klr neff-info add.neff
{ header := { packaging_version := 2,
header_size := 1024,
data_size := 30720,
kelp_version_major := 1,
kelp_version_minor := 0,
kelp_version_build := #[0, 0, ...],
num_tpb := 1,
hash := #[],
uuid := #[],
name := #[],
requested_tpb_count := 0,
tpb_per_node := #[],
pad := #[0, 0, ...] },
data := #[31, 139, ...

feat: Add basic NEFF codec

---

KLR.lean
KLR/Serde.lean
KLR/Serde/Attr.lean
KLR/Serde/Test.lean

This changes add a new attribute for constructors: "serde tag=n".  The motivation is to provide an easy way to define how constructors should be mapped to numeric values in serialized formats.

feat: add serde attribute for defining serialized formats

---

KLR/Trace/Tensor.lean

This patch allows Tensor.store API (which is connected to `nki.language.store`) to accept a more generic `Core.Value` type.
The motivation is tracing of interop/test/examples/matmul.py, specifically the `nki_matmul_basic_` function.
After apply #111, tracing the Python function was raising the following error message:
```
error:
line 44:
nl.store(result[i_out_p, i_out_f], value=result_sbuf)
^-- expecting tensor access
```
It is because its `value` keyword argument was having the following expression:
```
KLR.Trace.Term.expr (KLR.Core.Expr.value (KLR.Core.Value.var "5")) (KLR.Trace.TermType.obj `object)
```
which could not be converted to Access through the FromNKI typeclass.
The "5" temporary variable was emerging from the right hand side of the definition of `result_sbuf`:
``` …
```

feat: allow Tensor.store API to receive .var as value

---

KLR/Util/Archive/Archive.lean
KLR/Util/Archive/lean_archive.c

The current code crashes if the archive goes past the original buffer size. This change automatically resizes the buffer on write.

chore: resize archive buffer

---

KLR/BIR/Function.lean

Currently, `allocated` has a type `Option Bool` in `BIR.MemoryLocation`; it'd be fine to have it just `Bool`, following the type in the compiler.

chore: fix the type of allocated in BIR.MemoryLocation to Bool

---

KLR/Extract/Extract/C.lean
interop/nkic/ast_nki.h
interop/nkic/ast_python_core.h
interop/nkic/gather.c

The change removes the modifications to names when generating C code. This change makes names easier to deal with in the code generators.

chore: use Lean names in C code

---

KLR/Util.lean
KLR/Util/Enum.lean
KLR/Util/Sexp.lean
KLR/Util/SexpTest.lean

Following Ocaml sexp serialization: https://dev.realworldocaml.org/data-serialization.html Extends the Jane Street library by parsing both named and positional forms.
```
structure Foo where
x : Int
y : Bool
```
(5 true) and ((x 5) (y true)) are both valid encodings.
Comments welcome.
The biggest thing left to do is handle default arguments. That will come in a different PR. This one is complex enough.

feat: Add Sexp and ToSexp/FromSexp deriving

---

KLR/NKI/Basic.lean
KLR/Python.lean
KLR/Serde/Elab.lean
KLR/Util.lean
KLR/Util/Float.lean
KLR/Util/Sexp.lean
KLR/Util/SexpTest.lean

Add automatically derived instances of BEq, Repr, and conversions to and from CBOR, Json and Sexp to the Python and NKI abstract syntax trees.

chore: add standard derived instances to Python and NKI types

---

.github/workflows/ci.yml
.gitignore
bin/make-wheel
interop/LICENSE
interop/pyproject.toml
interop/setup.py

Brazil's Python3PBuildTool requires an [sdist](https://docs.python.org/3.10/distutils/sourcedist.html) of the python project, and it's currently using older version of setuptools (68.0.0).
Tweaks:
- Copy LICENSE file into python project dir (because it's simpler than relying on a custom script to inject it as the wheels are being built)
- Some tweaks to `pyproject.toml` to work with older setuptools:
- require exact setuptools version used in Brazil, so we catch incompatibilities sooner
- tweak how `license` was defined
- had to move `tool.setuptools.ext-modules` definitions to `setup.py`
Also, fixed our publishing steps to also upload a source distribution (aka "sdist", aka `*.tar.gz` file) to PyPI, in addition to the `*.whl` files. The sdist comes from the `CI / build (ubuntu-latest)` …

Upload sdist to PyPI, and tweaks to support Brazil's Python3PBuildTool

---

KLR.lean
KLR/KLR.lean
KLR/KLR/Basic.lean
KLR/KLR/Operators.lean

Pull in instructions to match nki isa
Most of the flags that had enums of 2 invariants are replaced with booleans.
Where we could collapse information from original enum + union structs, we collapsed down to
an inductive.
Right now there is no static information for inline arrays preserved. The generic list is used. This can
be replaced with a Vec with constraints on a size of a Vec if this information is more useful then cumbersome
to work around
For the operations we chose to define tensor view as
```
inductive TensorView where
| literal (freePattern: List APPair) (offset : Nat := 0) (dtype : Dtype) (parNum : Nat)
| reg (_ : Reg)
```
That should contain enough information reconstruct the original instructions with appropriate information
Most instructions have `src` and `dst` tensor …

Instruction integration

---

KLR/Util.lean
KLR/Util/Meta.lean
KLR/Util/Sexp.lean
KLR/Util/SexpTest.lean

I've had several bugs with typos in names. This is especially problematic when you rename a field in Lean, but forget to update the name in text files. This change throws on unknown names.
It also introduces a small Meta library that can be a home for common patterns of metaprogramming we use, so we don't need to remember dozens of library names.
Closes #199

chore: Have FromSexp throw on unknown fields

---

KLR/Core/Basic.lean
KLR/Core/Indexing.lean
KLR/Core/Operators.lean
KLR/Core/Tensor.lean
KLR/Trace/FromNKI.lean
KLR/Trace/ISA.lean
KLR/Trace/Python.lean
KLR/Trace/Tensor.lean
KLR/Trace/Types.lean

Changes the names of the the Tensor types:
- TensorSram -> TensorName  a abstract tensor
- TensorView -> TensorSram  a physical tensor in SRAM
- TensorRef now separates SBUF, PMEM, and HBM tensor types

refactor: change names of tensor types to more accurately reflect use

---

KLR/Trace/NKI.lean

A few operators are implemented but not enabled in the klr binary, this PR adds those operators into the list.

fix: enable missing ISA operators

---

KLR/NKI/Annotations.lean
KLR/NKI/Basic.lean
KLR/NKI/Simplify.lean

In Python, a chained comparison does not short-circuit. For example, if you write the expression:
1 < 0 < f()
then the function f will be called. This is different from logical and/or which does short-circuit. We also have the possibility of logical and/or on tensors, which does not short-circuit. This change introduces two new expression forms `conj` and `disj` which are used to represent Python short-circuit and/or. The normal land and lor binary operator do not short-circuit. This gives us what we need to lower logical operators, tensor operators, and chained comparison.

fix: chained comparison should not short-circuit

---

KLR/Trace/FromNKI.lean
KLR/Trace/Term.lean

Add support for offset for ndarray
``` python
def foo(a, a_tile):
a_tile = nl.ndarray(a.shape, a.dtype, offset=(42,42))
nisa.memset(dst=a_tile, name="foo", value=88.3, dtype=np.float32)
```
produces the following KLR
```
body := [KLR.Core.Stmt.oper
(KLR.Core.Operator.memSet
{ dst := KLR.Core.TensorRef.abstract
(KLR.Core.Access.pattern
{ tensor := { name := "tensor",
dtype := KLR.Core.Dtype.float32,
shape := { parDim := 10, freeDims := [10] },
address := { memory := KLR.Core.Memory.sbuf,
parSize := 10,
freeSize := 40,
parOffset := some 42,
freeOffset := some 42 },
freeElements := 10,
parWF := _,
freeWF := _ },
parNum := 10,
freePattern := [{ step := 1, num := 10 }],
offset := 0 }),
value := KLR.Core.Immediate.float 88.300003,
dtype := KLR.Core.Dtype.float32,
engine := …
```

feat: Add offset to ndarray

---

KLR/NKI/Basic.lean
KLR/NKI/Pretty.lean
KLR/NKI/Simplify.lean
KLR/Trace/NKI.lean

This change sets the name of input tensors to match the formal parameters of the top-level kernel they are applied to.

feat: set names of input tensors

---

KLR/NKI/Annotations.lean
KLR/NKI/Basic.lean
KLR/NKI/Pretty.lean
KLR/NKI/Simplify.lean
KLR/Trace/Builtin.lean
KLR/Trace/FromNKI.lean
KLR/Trace/ISA.lean
KLR/Trace/Lang.lean
KLR/Trace/NKI.lean
KLR/Trace/Python.lean
KLR/Trace/Term.lean
KLR/Trace/Types.lean

This changes the Term type to be more independent of the Core types.

refactor: do not use Core.Expr in Trace.Term

---

KLR/Trace/Term.lean

Introduce a new syntactic sugar which allows an access pattern to be specified with `t.ap(...)`.

feat: implement access pattern as an attribute of Access

---

interop/klr/frontend.c
interop/klr/frontend.h
interop/klr/gather.c
interop/klr/klr_ffi.c

Currently, we're copying the frontend Python C extension into a separate NKI repo. In the NKI repo, we've made a few changes to the C code, which makes it harder to take updates. You can't just copy/paste the files from KLR -> NKI. You need to do a finicky merge by hand.
Therefore, make the code identical between the two repos, using `#ifdef` for any logical differences. Now we can just copy/paste, instead of complex merges by hand.

chore: C code uses ifdefs for differences between KLR and NKI repos

---

KLR/Compile.lean
KLR/Core/Tensor.lean
KLR/Trace/FromNKI.lean
KLR/Trace/Lang.lean
KLR/Trace/Python.lean
KLR/Trace/Tensor.lean
KLR/Trace/Term.lean
KLR/Trace/Types.lean
Main.lean

Traces the following kernel:
``` python
def f():
c = nl.shared_constant(nl.identity(42, np.int8) + nl.identity(42, np.int8) + 1)
return c
```
Trace produced:
```
{ name := "test.f",
inputs := [],
outputs := [{ name := "tmp.2",
dtype := KLR.Core.Dtype.int8,
shape := { parDim := 42, freeDims := [42] },
address := { name := "tmp.2",
memory := KLR.Core.Memory.hbm,
parSize := 42,
freeSize := 42,
parOffset := none,
freeOffset := none },
freeElements := 42,
parWF := _,
freeWF := _ }],
bodies := [[
<< id_stuff>>
{ line := 0, column := 0, lineEnd := none, columnEnd := none }]],
sharedConstants := [{ name := "tmp.1", fileName := "./shared_constants/tmp.1.npy" },
{ name := "tmp.2", fileName := "./shared_constants/tmp.2.npy" }] }
```

shared constants

---

interop/klr/gather.c

Error messages must be descriptive and user-actionable.
I couldn't think of user-actionable advice for some of these (with, del, type, global, nonlocal) because I wasn't sure if we'd be supporting these soon or not. Please comment on the `TODO: ADVICE` lines with your suggestion.

fix: improve error messages for unsupported stmt kinds

---

interop/klr/__init__.py
interop/klr/frontend.c
interop/klr/frontend.h
interop/klr/gather.c

Currently, before you can call the Lean FFI version of trace, you need to serialize the Python AST to a file. This was leading to copy/pasted boilerplate in the tests I'm adding to the NeuronKernelInterface repo.
I added wrapper functions in `klr/__init__.py` to do that boilerplate, since boilerplate is a lot easier in python than C.
I also tweaked specialize so that extra args like `grid` are passed as actual keyword arguments, vs stuffing them all into an untyped `internal_kws` dict.  I also added a python wrapper for specialize, because it's easier to show arg names, type hints, comments etc in Python vs C.
Yes, it's a bit sloppy to just start throwing in wrapper functions, vs fixing the actual Kernel class to be nice, but this code won't live forever, and we can take these lessons to …

chore: simpler way to call trace from python

---

KLR/NKI/SimplifyOperators.lean
KLR/Trace/Lang.lean

Allows to trace kernels like `foo`
```python
def f():
a = hbm.view(nl.int8, (128,128))
b = hbm.view(nl.int8, (128,128))
builtin.isa.dma_copy(dst=a, src=b)
builtin.isa.dma_copy(dst=b, src=a)
return a
def foo():
a = f()
b = f()
return a, b
```

Feat: automatically generated tensor names from ptr and ndarray should be unique

---

KLR/NKI/Annotations.lean
KLR/NKI/Basic.lean
KLR/NKI/Pretty.lean
KLR/NKI/Simplify.lean
KLR/Python.lean
KLR/Trace/Lang.lean
KLR/Trace/NKI.lean
KLR/Trace/Python.lean
KLR/Trace/Term.lean
KLR/Trace/Types.lean
interop/klr/gather.c
interop/klr/lean_ast.h
interop/test/test_fstr.py

This change adds support for Python-style f-strings. This implementation does not support format specifiers, but it does support the repr conversion tag.  In the case of repr-conversion, we use the Lean repr format.

feat: add support for f-strings
